# Dome 

If you want to follow along in the parts studio, here is a link to my [original document](https://cvilleschools.onshape.com/documents/18c55e9aeb64057e8e0fbb6a/w/5c06b8e3c4dcf6e948152fa4/e/18df3578f02c775cfcadaef9?configuration=List_8xTqWDMkkCG2Mw%3D_2x2%3BList_ArQ6GsCPNSkQoQ%3DDefault%3BList_Izy0ldJ6UfParG%3DDefault%3BList_tmPjPdZ9wrB2lD%3DDefault&renderMode=0&uiState=6290d24be366b652b2773d0f). Navigate to the part studio called Weird Dome. The link puts you into the square bricks folder so youre going to want to go to home first. 

## Lets Begin 

You're going to want to make a new parts studio for this one because it's ver different from your normal brick. 

I debated whether or not I should include this one because its not a very common brick and doesn't share much with any other bricks, but I think it's probably important to learn just because of how weird it is. 

### 2x2 Dome 

This is the [Brick](https://www.bricklink.com/v2/catalog/catalogitem.page?P=553b#T=C) we're talking about

#### Disclaimer: This part is a bunch of nonsense numbers. Making legos is a bunch of trial and error because there are no offical dimensions for legos. Don't ask how I got the numbers I did because I really don't remember. 

First make a sketch on the front plane. Make a corner rectangle from the origin and delete the top line. 

Dimension the verticle lines to be #Height(9.7mm) - #Unit(1.5mm). I'll explain why later. 

Dimension the horizontal line to be #Length(8mm)

Now make a new top line but don't just connect it to the right side line. Instead dimension it to be (5mm + (#Unit/2))/2. Just copy the equation and drop it into onshape. 

Now make a conic arc from the bottom right corner to the end of the top line. Attach it's little arc point to the top of the right line and dimension the arc to be 0.45.

<img src="Photos/Dome(1).PNG">

Revolve the sketch around the origin mate connector. (If you're following along with the document you'll notice I have an extra sketch and did a sweep instead of a revolve. I honestly have no idea why I choose to do that but a revolve is easier) 

Now select the bottom face and select hollow. Set the Shell thickness to #Unit(1.5mm) 
